// Generated by github.com/sunfmin/goapigen
// DO NOT EDIT

(function(api, $, undefined ) {
	api.rpc = function(endpoint, input, callback) {
		var methodUrl = api.baseurl + endpoint;
		var message = JSON.stringify(input);
		var req = $.ajax({
			type: "POST",
			url: methodUrl,
			contentType:"application/json; charset=utf-8",
			dataType:"json",
			processData: false,
			data: message
		});
		req.done(function(data, textStatus, jqXHR) {
			callback(data);
		});
	};
})( window.todoapi = window.todoapi || {}, jQuery);



(function( api, undefined ) {

	api.UserService = function() {};

	api.UserService.prototype.GetTodoLists = function(callback) {
		api.rpc("/UserService/GetTodoLists.json", {"This": this, "Params": {  }}, function(data){
			callback(data.List, data.Err)
		});
		return;
	}

	api.UserService.prototype.GetTodoItems = function(listId, callback) {
		api.rpc("/UserService/GetTodoItems.json", {"This": this, "Params": { "ListId": listId }}, function(data){
			callback(data.List, data.Err)
		});
		return;
	}

	api.UserService.prototype.PutTodoList = function(name, callback) {
		api.rpc("/UserService/PutTodoList.json", {"This": this, "Params": { "Name": name }}, function(data){
			callback(data.Err)
		});
		return;
	}

	api.UserService.prototype.CreateTodo = function(listId, name, callback) {
		api.rpc("/UserService/CreateTodo.json", {"This": this, "Params": { "ListId": listId, "Name": name }}, function(data){
			callback(data.Err)
		});
		return;
	}

	api.UserService.prototype.DoneTodo = function(todoId, callback) {
		api.rpc("/UserService/DoneTodo.json", {"This": this, "Params": { "TodoId": todoId }}, function(data){
			callback(data.Err)
		});
		return;
	}

	api.UserService.prototype.UndoneTodo = function(todoId, callback) {
		api.rpc("/UserService/UndoneTodo.json", {"This": this, "Params": { "TodoId": todoId }}, function(data){
			callback(data.Err)
		});
		return;
	}

	api.AppService = function() {};

	api.AppService.prototype.GetUserService = function(email, password) {
		var r = new api.UserService();
		r.Email = email;
		r.Password = password;
		return r;
	}


}( window.todoapi = window.todoapi || {} ));

